/**
 * Fetch full content for notes in your rednote.com "Liked" tab, for use as
 * video-script source material (one note = one "post + reader replies" clip).
 *
 * DEPENDS ON: OpenCLI (https://github.com/jackwener/opencli), a separate tool
 * installed locally at ~/.opencli (see OPENCLI_BIN below). This script is a
 * thin orchestrator around OpenCLI's `rednote note / comments / download`
 * commands — it does not talk to rednote.com directly itself.
 *
 * PREREQUISITES
 * 1. OpenCLI must be installed and its browser bridge extension connected
 *    (check with: node ~/.opencli/node_modules/@jackwener/opencli/dist/src/main.js doctor).
 * 2. You must be logged into rednote.com (NOT xiaohongshu.com — different
 *    domain/cookies) in the Chrome window OpenCLI's extension controls.
 *    Check with: node <opencli bin> rednote whoami --format json
 * 3. LIKED_LIST_PATH (liked_notes.json) must already exist — it's the index
 *    of what to fetch. It is NOT produced by this script. It's generated by
 *    opening https://www.rednote.com/user/profile/<your-id>?tab=liked in the
 *    OpenCLI-bound browser, scrolling to load everything, and reading
 *    window.__INITIAL_STATE__.user.notes out of the page (there is no
 *    dedicated OpenCLI "liked" command for the rednote.com domain — only for
 *    xiaohongshu.com). Re-generate this file manually if you've liked new
 *    notes since the last run; this script only reads it, never refreshes it.
 *
 * OUTPUT (per note, under output/rednote/liked/<note-id>/):
 *   note.json      — raw OpenCLI `rednote note` output
 *   comments.json  — raw OpenCLI `rednote comments --with-replies` output
 *   *.jpg / *.mp4  — downloaded media
 *   note.md        — flattened, agent-readable summary (title/author/media/
 *                    body/comments in one linear doc) — this is the file to
 *                    hand to an agent as video-script material, not the JSON.
 * manifest.json (output/rednote/liked/manifest.json) tracks which note ids
 * have already been fetched successfully, so re-running this script only
 * processes new/failed notes — it never re-fetches a note already marked ok.
 *
 * SAFETY DESIGN (rednote.com's risk control WILL block bursty scripted
 * traffic — this was learned the hard way; an earlier tight loop with no
 * delay got 25/36 notes blocked in under 2 minutes):
 * - Notes are processed strictly one at a time, never concurrently.
 * - Randomized delay between notes (30-90s; every 5th note takes a longer
 *   3-5min break) instead of a fixed interval, to avoid a robotic cadence.
 * - Two distinct anomaly signals are handled differently:
 *     - HARD BLOCK (title === "Security Verification", or both author and
 *       content empty, or expected-comment-count > 0 but 0 comments came
 *       back): treated as a real risk-control interstitial. The script
 *       stops immediately, marks that note "blocked" in the manifest, and
 *       leaves the rest of the queue for the next run. It does NOT push
 *       through further notes once this happens.
 *     - SOFT ANOMALY (title selector caught a transient "Reminder" UI toast
 *       instead of the real title, but author/content look real): not
 *       treated as a block. The title is corrected using the known-good
 *       title from liked_notes.json and processing continues normally.
 * - Safe to re-run any time (e.g. as a daily cron/task) — it will always
 *   pick up wherever the last run left off via manifest.json.
 *
 * USAGE:  node scripts/rednote_liked_fetch.js
 */
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const OPENCLI_BIN = path.join(process.env.HOME, '.opencli/node_modules/@jackwener/opencli/dist/src/main.js');
const BASE_DIR = path.join(__dirname, '..', 'output', 'rednote', 'liked');
const LIKED_LIST_PATH = path.join(BASE_DIR, 'liked_notes.json');
const MANIFEST_PATH = path.join(BASE_DIR, 'manifest.json');

function opencli(args) {
  const res = spawnSync('node', [OPENCLI_BIN, ...args], { encoding: 'utf8', maxBuffer: 1024 * 1024 * 20 });
  return { status: res.status, stdout: res.stdout || '', stderr: res.stderr || '' };
}

function readJson(p, fallback) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; }
}

function fieldValue(rows, field) {
  const r = Array.isArray(rows) ? rows.find(x => x.field === field) : null;
  return r ? String(r.value ?? '') : '';
}

// Hard block: real risk-control interstitial (or totally empty page). Always stop on this.
function isNoteBlocked(rows) {
  if (!rows || !Array.isArray(rows) || rows.length === 0) return true;
  const title = fieldValue(rows, 'title').trim();
  const author = fieldValue(rows, 'author').trim();
  const content = fieldValue(rows, 'content').trim();
  if (title === 'Security Verification') return true;
  if (!author && !content) return true;
  return false;
}

// Soft anomaly: title selector grabbed a transient UI toast instead of the real title,
// but author/content are present and real. Not a block — just use the known-good title
// from the liked list and note that a correction happened.
function resolveTitle(rows, expectedTitle) {
  const title = fieldValue(rows, 'title').trim();
  if (expectedTitle && title !== expectedTitle.trim()) {
    return { title: expectedTitle.trim(), corrected: true, rawTitle: title };
  }
  return { title, corrected: false };
}

function flattenMediaIfNested(noteDir, id) {
  const nested = path.join(noteDir, id);
  if (fs.existsSync(nested) && fs.statSync(nested).isDirectory()) {
    for (const f of fs.readdirSync(nested)) {
      fs.renameSync(path.join(nested, f), path.join(noteDir, f));
    }
    fs.rmdirSync(nested);
  }
}

function listMedia(noteDir) {
  if (!fs.existsSync(noteDir)) return [];
  return fs.readdirSync(noteDir)
    .filter(f => /\.(jpg|jpeg|png|webp|mp4|mov)$/i.test(f))
    .sort();
}

function renderComments(comments) {
  if (!comments || comments.length === 0) return '(无评论 / 未抓到评论)';
  const lines = [];
  let n = 0;
  for (const c of comments) {
    if (!c.is_reply) {
      n += 1;
      lines.push(`${n}. **${c.author}**（${c.likes}赞，${c.time}）：${c.text}`);
    } else {
      lines.push(`   ↳ 回复${c.reply_to ? ' @' + c.reply_to : ''}：${c.text}`);
    }
  }
  return lines.join('\n');
}

function generateMarkdown(entry, noteRows, comments, mediaFiles) {
  const { title } = resolveTitle(noteRows, entry.title);
  const author = fieldValue(noteRows, 'author') || entry.author;
  const content = fieldValue(noteRows, 'content');
  const likes = fieldValue(noteRows, 'likes') || entry.likes;
  const collects = fieldValue(noteRows, 'collects');
  const commentsCount = fieldValue(noteRows, 'comments');
  const tags = fieldValue(noteRows, 'tags');

  const mediaSection = mediaFiles.length
    ? mediaFiles.map((f, i) => /\.(mp4|mov)$/i.test(f) ? `[视频${i + 1}](./${f})` : `![图${i + 1}](./${f})`).join('\n')
    : '(无媒体文件)';

  return `# ${title}

作者：${author}　赞：${likes}　收藏：${collects}　评论：${commentsCount}
标签：${tags}
原文链接：${entry.url}

## 媒体
${mediaSection}

## 正文
${content}

## 评论
${renderComments(comments)}
`;
}

function validateExisting(entry) {
  const noteDir = path.join(BASE_DIR, entry.id);
  const noteJsonPath = path.join(noteDir, 'note.json');
  if (!fs.existsSync(noteJsonPath)) return null;
  const rows = readJson(noteJsonPath, null);
  if (isNoteBlocked(rows)) return null;
  const commentsPath = path.join(noteDir, 'comments.json');
  const comments = readJson(commentsPath, []);
  const expectedCommentCount = parseInt(fieldValue(rows, 'comments').replace(/[^\d]/g, ''), 10) || 0;
  if (expectedCommentCount > 0 && comments.length === 0) return null; // mismatch -> treat as suspect
  return { rows, comments };
}

function sleepSeconds(s) {
  spawnSync('sleep', [String(s)]);
}

function main() {
  const likedNotes = readJson(LIKED_LIST_PATH, []);
  let manifest = readJson(MANIFEST_PATH, {});

  log(`总计 ${likedNotes.length} 篇点赞笔记`);

  // Pass 1: validate + flatten + regenerate markdown for anything already valid on disk.
  const todo = [];
  for (const entry of likedNotes) {
    const noteDir = path.join(BASE_DIR, entry.id);
    flattenMediaIfNested(noteDir, entry.id);
    const valid = validateExisting(entry);
    if (valid) {
      const media = listMedia(noteDir);
      fs.writeFileSync(path.join(noteDir, 'note.md'), generateMarkdown(entry, valid.rows, valid.comments, media));
      manifest[entry.id] = { title: entry.title, status: 'ok', fetchedAt: manifest[entry.id]?.fetchedAt || 'unknown' };
    } else {
      todo.push(entry);
    }
  }
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
  log(`已验证有效: ${likedNotes.length - todo.length} 篇；待处理: ${todo.length} 篇`);

  // Pass 2: process todo list one at a time, stop on first block.
  let processed = 0;
  for (const entry of todo) {
    const noteDir = path.join(BASE_DIR, entry.id);
    fs.mkdirSync(noteDir, { recursive: true });
    log(`处理中: [${entry.id}] ${entry.title}`);

    const noteRes = opencli(['rednote', 'note', entry.url, '--format', 'json', '--site-session', 'persistent']);
    let noteRows;
    try { noteRows = JSON.parse(noteRes.stdout); } catch { noteRows = null; }

    if (isNoteBlocked(noteRows)) {
      manifest[entry.id] = { title: entry.title, status: 'blocked', lastAttempt: 'stopped-here' };
      fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
      log(`STOPPED — 侦测到疑似风控拦截，笔记: [${entry.id}] ${entry.title}`);
      log(`已处理 ${processed}/${todo.length}（本轮）。剩余留到下次继续。`);
      return;
    }
    const titleCheck = resolveTitle(noteRows, entry.title);
    if (titleCheck.corrected) {
      log(`标题已修正: [${entry.id}] 抓到的是 "${titleCheck.rawTitle}"，改用列表里的 "${titleCheck.title}"`);
    }
    fs.writeFileSync(path.join(noteDir, 'note.json'), JSON.stringify(noteRows, null, 2));

    const commentsRes = opencli(['rednote', 'comments', entry.url, '--limit', '50', '--with-replies', '--format', 'json', '--site-session', 'persistent']);
    let comments;
    try { comments = JSON.parse(commentsRes.stdout); } catch { comments = []; }
    const expectedCommentCount = parseInt(fieldValue(noteRows, 'comments').replace(/[^\d]/g, ''), 10) || 0;
    if (expectedCommentCount > 0 && comments.length === 0) {
      manifest[entry.id] = { title: entry.title, status: 'blocked', lastAttempt: 'comments-mismatch' };
      fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
      log(`STOPPED — 评论数对不上（预期${expectedCommentCount}条，实际0条），疑似拦截: [${entry.id}] ${entry.title}`);
      log(`已处理 ${processed}/${todo.length}（本轮）。剩余留到下次继续。`);
      return;
    }
    fs.writeFileSync(path.join(noteDir, 'comments.json'), JSON.stringify(comments, null, 2));

    opencli(['rednote', 'download', entry.url, '--output', BASE_DIR, '--site-session', 'persistent']);
    flattenMediaIfNested(noteDir, entry.id);
    const media = listMedia(noteDir);

    fs.writeFileSync(path.join(noteDir, 'note.md'), generateMarkdown(entry, noteRows, comments, media));
    manifest[entry.id] = { title: entry.title, status: 'ok', fetchedAt: new Date().toISOString() };
    fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
    processed += 1;
    log(`OK [${entry.id}] ${entry.title} — 媒体${media.length}个，评论${comments.length}条`);

    const isLast = entry === todo[todo.length - 1];
    if (!isLast) {
      const longBreak = processed % 5 === 0;
      const delay = longBreak ? (180 + Math.random() * 120) : (30 + Math.random() * 60);
      log(`休息 ${Math.round(delay)} 秒${longBreak ? '（长休息）' : ''}...`);
      sleepSeconds(Math.round(delay));
    }
  }
  log(`全部完成：本轮处理 ${processed}/${todo.length} 篇，全部成功，没有触发拦截。`);
}

function log(msg) {
  console.log(`[${new Date().toISOString()}] ${msg}`);
}

main();
